"""change song for nullable

Revision ID: 0ce86d14952c
Revises: 541c275d9e88
Create Date: 2026-03-08 16:57:20.967546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce86d14952c'
down_revision: Union[str, Sequence[str], None] = '541c275d9e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'preview_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('preview_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
