"""create timezone

Revision ID: 193a28ad14ba
Revises: c58332a6132a
Create Date: 2026-03-06 04:33:47.046176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '193a28ad14ba'
down_revision: Union[str, Sequence[str], None] = 'c58332a6132a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'emotion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'mood_color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reviews', 'mood_color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'emotion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
