"""added preview_url to songs

Revision ID: 35b76615ec24
Revises: 86511f80136f
Create Date: 2026-02-24 03:52:07.388918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b76615ec24'
down_revision: Union[str, Sequence[str], None] = '86511f80136f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('preview_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'preview_url')
    # ### end Alembic commands ###
