"""change structure

Revision ID: 50e2918043e9
Revises: 84e3e2ab9e24
Create Date: 2026-03-03 09:03:33.925156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e2918043e9'
down_revision: Union[str, Sequence[str], None] = '84e3e2ab9e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('favorites', 'spotify_id')
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'emotion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'mood_color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'spotify_id')
    op.drop_column('reviews', 'update_at')
    op.add_column('songs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('songs', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('songs', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('spotify_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('reviews', 'mood_color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'emotion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reviews', 'updated_at')
    op.add_column('favorites', sa.Column('spotify_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('favorites', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
