"""change structure5

Revision ID: 81da00d89913
Revises: 3f6f8090d755
Create Date: 2026-03-03 10:55:22.791194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81da00d89913'
down_revision: Union[str, Sequence[str], None] = '3f6f8090d755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'updated_at')
    op.alter_column('songs', 'artist_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'artist_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('favorites', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
