"""added attribute in favorite table

Revision ID: 84e3e2ab9e24
Revises: 9c8dfa34272b
Create Date: 2026-03-02 20:00:18.623365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e3e2ab9e24'
down_revision: Union[str, Sequence[str], None] = '9c8dfa34272b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('spotify_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'spotify_id')
    # ### end Alembic commands ###
