"""add cascade delete to song fk

Revision ID: 899a364baad5
Revises: 087e1c9bd4ed
Create Date: 2026-03-04 13:46:48.266568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899a364baad5'
down_revision: Union[str, Sequence[str], None] = '087e1c9bd4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favorites_song_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_song_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_song_id_fkey'), 'reviews', 'songs', ['song_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_song_id_fkey'), 'favorites', 'songs', ['song_id'], ['id'])
    # ### end Alembic commands ###
