"""insert colounm

Revision ID: 9c8dfa34272b
Revises: ae87c2af236b
Create Date: 2026-03-02 19:36:50.633947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8dfa34272b'
down_revision: Union[str, Sequence[str], None] = 'ae87c2af236b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.add_column('songs', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'update_at')
    op.drop_column('reviews', 'update_at')
    op.drop_column('favorites', 'updated_at')
    # ### end Alembic commands ###
