"""remove icon_url from emotions

Revision ID: b1c371b8be19
Revises: 899a364baad5
Create Date: 2026-03-05 13:00:10.495180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c371b8be19'
down_revision: Union[str, Sequence[str], None] = '899a364baad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotions', 'icon_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('icon_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
