"""change structure2

Revision ID: b2d1d74cbb2d
Revises: 50e2918043e9
Create Date: 2026-03-03 10:51:46.895398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d1d74cbb2d'
down_revision: Union[str, Sequence[str], None] = '50e2918043e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'artist_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_songs_artist_name'), 'songs', ['artist_name'], unique=False)
    op.create_index(op.f('ix_songs_song_name'), 'songs', ['song_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_song_name'), table_name='songs')
    op.drop_index(op.f('ix_songs_artist_name'), table_name='songs')
    op.alter_column('songs', 'artist_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
