"""Added users table5

Revision ID: d4345cdb4bdb
Revises: 193a28ad14ba
Create Date: 2026-03-07 19:25:12.135131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4345cdb4bdb'
down_revision: Union[str, Sequence[str], None] = '193a28ad14ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('link_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'link_url')
    # ### end Alembic commands ###
