"""update table review for spotify_id

Revision ID: e81230fcb1a2
Revises: 35b76615ec24
Create Date: 2026-03-02 16:03:09.569698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81230fcb1a2'
down_revision: Union[str, Sequence[str], None] = '35b76615ec24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('spotify_id', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('preview_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'preview_url')
    op.drop_column('reviews', 'spotify_id')
    # ### end Alembic commands ###
